[package]
name = "jian-ui"
version.workspace = true
edition.workspace = true

[dependencies]
egui = { workspace = true }
chrono = { workspace = true }
image = { workspace = true }
resvg = { workspace = true }
tracing = { workspace = true }
jian-core = { workspace = true }
jian-config = { workspace = true }
jian-map = { workspace = true }
jian-travel = { workspace = true }
jian-net = { workspace = true }
